version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: goon-video-astro
    restart: always
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    networks:
      - proxy-network # On utilise le nom interne défini en bas
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.goon-video.rule=Host(`goonvideo.fr`) || Host(`www.goonvideo.fr`)"
      
      # Configuration SSL (Le Cadenas)
      - "traefik.http.routers.goon-video.entrypoints=websecure"
      - "traefik.http.routers.goon-video.tls=true"
      - "traefik.http.routers.goon-video.tls.certresolver=myresolver"

      # Redirection automatique HTTP -> HTTPS
      - "traefik.http.routers.goon-video-http.rule=Host(`goonvideo.fr`) || Host(`www.goonvideo.fr`)"
      - "traefik.http.routers.goon-video-http.entrypoints=web"
      - "traefik.http.routers.goon-video-http.middlewares=astro-redirect"
      - "traefik.http.middlewares.astro-redirect.redirectscheme.scheme=https"

networks:
  proxy-network:
    external: true
    name: goon_web